name: Deploy to Skynet

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    env:
      REACT_APP_SUPPORTED_ETHEREUM_NETWORKS: 'kovan,mumbai,fuji,mainnet,polygon,avalanche'
      REACT_APP_DEFAULT_ETHEREUM_NETWORK: 'mainnet'
      REACT_APP_ENABLE_CACHING_BACKEND: 'true'
      REACT_APP_RATES_HISTORY_ENDPOINT: 'https://aave-api-v2.aave.com/data/rates-history'
      NGINX_MODE: 'staging'

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: npm ci

      - run: npm run build

      - name: 'Deploy to Skynet'
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
          try-files: 'index.html /index.html'
